### ISSUE TITLE
Dashboard import fails when it contains a merge result tile

### ISSUE THREAD

**Issue by n0rritt** [looker-open-source/gzr#151]
We are experience this error when we try to import a dashboard that contains merge result tiles:
```
Traceback (most recent call last):
        21: from /home/hai/.gem/ruby/2.5.0/bin/gzr:23:in `<main>'
        20: from /home/hai/.gem/ruby/2.5.0/bin/gzr:23:in `load'
        19: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/exe/gzr:36:in `<top (required)>'
        18: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        17: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        16: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        14: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        13: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        12: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        11: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        10: from /home/hai/.gem/ruby/2.5.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
         9: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard.rb:78:in `import'
         8: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:50:in `execute'
         7: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/modules/session.rb:249:in `with_session'
         6: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
         5: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/modules/filehelper.rb:88:in `read_file'
         4: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:94:in `block (2 levels) in execute'
         3: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:94:in `map'
         2: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:108:in `block (3 levels) in execute'
         1: from /home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:108:in `each'
/home/hai/.gem/ruby/2.5.0/gems/gazer-0.2.56/lib/gzr/commands/dashboard/import.rb:112:in `block (4 levels) in execute': undefined method `dashboard_layout_id' for nil:NilClass (NoMethodError)
```
we are using:
* gazer v0.2.56
* Looker Release 22.16.31

**Comment by jannarobertson-bytecode** [comment]
@n0rritt thank you for reporting the issue and for including the versions; we will investigate this issue and respond.

**Comment by ddaugherty** [comment]
Hello @n0rritt, 

I have tested this with a dashboard containing a single merge result tile with no issues.  Can you verify if this happens with any dashboard with a merge result tile or is it limited to a single specific dashboard.  

Also, given the the specific error, you may want to take a look at the dashboard_layout sections of the file you are importing and either use the api explorer or a direct api call (dashboard_layout) for those dashboard_layout_ids to make sure they exit, etc. 

Thanks. 
@ddaugherty

**Comment by jannarobertson-bytecode** [comment]
@n0rritt we are closing out this issue, as it wasn't able to be replicated.  Please reopen or open new issue if you experience any issues with dashboard_layout_id not working as expected. Thank you!
