### ISSUE TITLE
unable to run the tool

### ISSUE THREAD

**Issue by jefimm** [looker-open-source/gzr#157]
```
docker run --rm -ti ruby bash
gem install gazer
gzr --version
v0.2.56
gzr space export 1 --persistent true --host=host --client-id=******* --client-secret=*******

/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/middleware_registry.rb:57:in `lookup_middleware': :net_http_persistent is not registered on Faraday::Adapter (Faraday::Error)
	from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:113:in `adapter'
	from /usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `adapter'
	from /usr/local/bundle/gems/gazer-0.2.56/lib/gzr/modules/session.rb:141:in `block in login'
	from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/connection.rb:91:in `initialize'
	from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday.rb:98:in `new'
	from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday.rb:98:in `new'
	from /usr/local/bundle/gems/gazer-0.2.56/lib/gzr/modules/session.rb:139:in `login'
	from /usr/local/bundle/gems/gazer-0.2.56/lib/gzr/modules/session.rb:248:in `with_session'
	from /usr/local/bundle/gems/gazer-0.2.56/lib/gzr/commands/space/export.rb:51:in `execute'
	from /usr/local/bundle/gems/gazer-0.2.56/lib/gzr/commands/space.rb:82:in `export'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/gazer-0.2.56/exe/gzr:36:in `<top (required)>'
	from /usr/local/bundle/bin/gzr:25:in `load'
	from /usr/local/bundle/bin/gzr:25:in `<main>'

```

**Comment by danieldiamond** [comment]
seems this issue is appearing everywhere atm
https://github.com/looker-open-source/looker_deployer/issues/114

some historical issues relating as well: https://github.com/looker-open-source/looker_deployer/issues/79

**Comment by drstrangelooker** [comment]
I just pushed a new version, 0.2.58. Please try that one.

Thanks
Mike

**Comment by drstrangelooker** [comment]
@jefimm can you confirm this is working for you now so I can close? Thanks.

**Comment by jefimm** [comment]
thank you, we are good
