### ISSUE TITLE
Dashboard import containing merged results fails

### ISSUE THREAD

**Issue by MartinGuindon** [looker-open-source/gzr#59]
I'm encountering an error when trying to import a dashboard with tiles leveraging merged results.

```
/Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/modules/look.rb:164:in `create_merge_result': private method `select' called for "#<Sawyer::Resource:0x00007fc1740a87b8>":String (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:228:in `process_dashboard_element'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:187:in `sync_dashboard_element'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:75:in `block (3 levels) in execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/command.rb:251:in `block in pairs'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/command.rb:251:in `collect'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/command.rb:251:in `pairs'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:74:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/modules/filehelper.rb:88:in `read_file'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/modules/session.rb:207:in `with_session'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard/import.rb:50:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/lib/gzr/commands/dashboard.rb:76:in `import'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.33/exe/gzr:36:in `<top (required)>'
	from /usr/local/bin/gzr:22:in `load'
	from /usr/local/bin/gzr:22:in `<main>'
```

I've successfully imported "regular" dashboards. Running gzr version 0.2.33.

I can provide the exported file privately if needed.

**Comment by drstrangelooker** [comment]
If you can email me the file that would be great. My email is in https://github.com/looker-open-source/gzr/blob/master/CONTRIBUTING.md at the very end.

**Comment by MartinGuindon** [comment]
Done, thank you Mike! :)

**Comment by drstrangelooker** [comment]
Fixed in the latest release. The problem was the export, not the import.

https://github.com/looker-open-source/gzr/commit/8d7fb3476e1ee78124c7462aed320ae84197c155

**Comment by kisa500** [comment]
@drstrangelooker I am on version 0.2.40 and seem to be having a similar problem, but specifically regarding filters not being applied to the merged result set. Should I submit as a new issue? 
Thank you,
