### ISSUE TITLE
Bug when using dashboards with merge queries

### ISSUE THREAD

**Issue by trevordjones** [looker-open-source/gzr#80]
Hello,

I believe I found a bug regarding `color_palette_lookup!` I found it because we are unable to deploy dashboards with merged queries. Here's the full stack trace:

```
/app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:251:in `update_color_palette!': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/modules/look.rb:186:in `block (2 levels) in create_merge_result'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:189:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `block in find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `block in find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `block in find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `block in find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `block in find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:191:in `find_color_palette_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/modules/look.rb:185:in `block in create_merge_result'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/command.rb:171:in `find_vis_config_reference'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/modules/look.rb:184:in `create_merge_result'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:209:in `process_dashboard_element'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:75:in `block (3 levels) in execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:71:in `map'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:71:in `block (2 levels) in execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/modules/filehelper.rb:88:in `read_file'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/modules/session.rb:207:in `with_session'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard/import.rb:50:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/lib/gzr/commands/dashboard.rb:76:in `import'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/gems/gazer-0.2.43/exe/gzr:36:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/gzr:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/gzr:23:in `<main>'
```

From here https://github.com/looker-open-source/gzr/blob/1a122c08285fa5440db3baca2aa9229d6982d7c4/lib/gzr/command.rb#L196

We are getting the `nil` value because a Sawyer object does not respond to `has_key?`.
```
pry(main) > obj = looker_client.default_color_collection
pry(main) > obj.class
Sawyer::Resource < Object
pry(main)> obj.respond_to?(':has_key')
false
```

**Comment by VyshnaviCR** [comment]
We are facing the same issue any fixes done here ?

**Comment by michaelcramer** [comment]
@trevordjones is this still an issue?  If so, could you please reply with the version of Looker and Ruby you're using?  Thanks!

**Comment by jannarobertson-bytecode** [comment]
@trevordjones due to the report's age, we are closing out this issue.  We encourage you to open another if you're still finding this to be unresolved; please include the Looker and Ruby/Gazer versions you're using.  Thank you!
