### ISSUE TITLE
Dashboard import error

### ISSUE THREAD

**Issue by umairda** [looker-open-source/gzr#82]
I'm trying to import a dashboard from a json file as follows: 
```
gzr dashboard import Space_2129_Sales.json 11 --host {host} --port 443 --debug
```

but I get the following error:
```
Error search_dashboards_by_title({
  "title": null,
  "space_id": "11"
})
An error has occurred.

/Library/Ruby/Gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/response/raise_error.rb:39:in `on_complete'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
/Library/Ruby/Gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
/Library/Ruby/Gems/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
/Library/Ruby/Gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client.rb:304:in `request'
/Library/Ruby/Gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client.rb:96:in `get'
/Library/Ruby/Gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:139:in `invoke_remote'
/Library/Ruby/Gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:106:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/dashboard.rb:73:in `search_dashboards_by_title'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/import.rb:125:in `sync_dashboard'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/import.rb:56:in `block (2 levels) in execute'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/filehelper.rb:88:in `read_file'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:207:in `with_session'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/import.rb:50:in `execute'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard.rb:76:in `import'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'
/usr/local/bin/gzr:23:in `load'
/usr/local/bin/gzr:23:in `<main>'
```

**Comment by drstrangelooker** [comment]
It looks like you are passing in a Space json file, not a Dashboard json file.
