### ISSUE TITLE
Dashboard transformation fails

### ISSUE THREAD

**Issue by PedroMartinSteenstrup** [looker-open-source/gzr#83]
Tried from mac and ubuntu
gazer (0.2.44)

All the other commands work fine for me, except when I try to pass transformations

`gzr dashboard cat 7 --no-ssl --host xxx.xx.xx.xxx --transform ~/gzr_outputs/json_replacements.json`

the file contains just this taken from the project page and names changed to fit mines:

```
{"replacements": [{
                        "\"model\": \"main\",": "\"model\": \"target\","
                }
        ]
}
```

Returns the following error
```
Traceback (most recent call last):
	17: from /usr/local/bin/gzr:23:in `<main>'
	16: from /usr/local/bin/gzr:23:in `load'
	15: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'
	14: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 8: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 7: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 6: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 5: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard.rb:60:in `cat'
	 4: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/cat.rb:45:in `execute'
	 3: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:207:in `with_session'
	 2: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/cat.rb:81:in `block in execute'
	 1: from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/filehelper.rb:88:in `read_file'
/var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/dashboard/cat.rb:83:in `block (2 levels) in execute': undefined method `collect!' for nil:NilClass (NoMethodError)```

**Comment by DeltaHotel** [comment]
I have this issue as well. Also on a mac using gazer v0.2.44

**Comment by wrenchpilot** [comment]
Same error here.

**Comment by wrenchpilot** [comment]
I think I found the problem here, "dashboard_elements" must be defined in your transform, even if empty.

```
{
    "dashboard_elements": [],    
    "replacements": [{
                        "\"model\": \"main\",": "\"model\": \"target\","
     }]
}

**Comment by michaelcramer** [comment]
@PedroMartinSteenstrup is this still an issue or did the above comment resolve?  Thanks!

**Comment by jannarobertson-bytecode** [comment]
@PedroMartinSteenstrup as this issue is very outdated and we haven't heard back, we are closing it out.  Please open another issue if you are still having difficulty with this or anything else; please include the Looker and Gazer/Ruby versions you're using.  Thank you!
