### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by CJoseph29** [looker-open-source/gzr#91]
I got the Ro-gazer ide to work but when i enter my instance name i get this error
Traceback (most recent call last):
  File "MYHOMEPATH\Ro-Gazer\ro-gazer.py", line 371, in <module>
    return_code = gzr_core_functions.test_connection(host)
  File "MYHOMEPATH\Ro-Gazer\gzr_core_functions.py", line 17, in test_connection
    return subprocess.run(['gzr', 'user', 'me', '--host=' + host], stdout = subprocess.PIPE, stderr = subprocess.PIPE).returncode
  File "MYHOMEPATH\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "MYHOMEPATH\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "MYHOMEPATH\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified.

I am fairly new to this it would be great to have help to solve this.

**Comment by ddaugherty** [comment]
Hello.   I see this may be a [Ro-gazer issue,](https://github.com/Ro-Data/Ro-Gazer) not specifically related to Gazer.  You may want to make sure you are using the version of gazer that is specified by Ro-gazer but otherwise, that WinError 2 seems to be coming from Ro-gazer (Python).   

On the other hand, if you wish to try that gzr user command directly in Gazer, simply run : 
`gzr user me --host={your-looker-instance}.looker.com `
